--primarygoogle
jamesgurung/timetable-calendar-generator pull request #5
Opened 2019-08-17 20:38 UTC by timmy-mac

Add to primary calendar and delete 'My timetable', if present.

2019-08-17 22:05 UTC, jamesgurung requested changes
Thank you for your contribution!

After you forked the project, I made some minor formatting and performance changes (see a9bbefe25bf3c7a589f20a3cd38f700858d2094c and dd042c2b60498baef014a1e978d2e9673bcde4aa). It looks like you merged these upstream changes, but they were then overwritten by another commit in your fork, back to the old versions. Most of my review comments are just to put this right (I've used the word "revert" to indicate).

2019-08-17 22:05 UTC, jamesgurung commented on README.md
> +1. Ensure you have the [.NET Core 3.0 runtime](https://dotnet.microsoft.com/download) installed.
Revert
```suggestion
1. Ensure you have the [.NET Core 3.0 runtime](https://dotnet.microsoft.com/download/dotnet-core) installed.
```

2019-08-17 22:05 UTC, jamesgurung commented on makecal.sln
> +VisualStudioVersion = 15.0.26724.1
Revert
```suggestion
VisualStudioVersion = 16.0.29123.89
```

2019-08-17 22:05 UTC, jamesgurung commented on makecal.sln
> +# Visual Studio 15
Revert
```suggestion
# Visual Studio Version 16
```

2019-08-17 22:05 UTC, jamesgurung commented on src/ArgumentParser.cs
> +            System.Threading.Thread.Sleep(12000);
```suggestion
            if (Console.ReadKey().Key != ConsoleKey.Y)
            {
              Console.Write("\n\nCancelled.");
              Environment.Exit(0);
              return;
            }
            Console.WriteLine("\n");
```

2019-08-17 22:05 UTC, jamesgurung commented on src/ArgumentParser.cs
> +            Console.WriteLine("WARNING: The --primarygoogle option deletes any calendars named 'My timetable'.\nIt will also input events into users' primary calendars...\n\nHit ctrl+c or close the w
```suggestion
            Console.WriteLine("WARNING: This will edit users' primary calendars. Continue? [y/n] ");
```

2019-08-17 22:05 UTC, jamesgurung commented on src/ArgumentParser.cs
> +            SetOutputFormat(OutputType.PrimaryGoogle, "PrimaryGoogle", 40);
The second argument is just used in a text string later.
```suggestion
            SetOutputFormat(OutputType.PrimaryGoogle, "Google", 40);
```

2019-08-17 22:05 UTC, jamesgurung commented on src/ArgumentParser.cs
> +        throw new ArgumentException("Use only one flag: --csv or --ical or --google or --primary-google");
```suggestion
        throw new ArgumentException("Use only one flag: --csv or --ical or --google or --primarygoogle");
```

2019-08-17 22:05 UTC, jamesgurung commented on src/CalendarWriterFactory.cs
> +      else if (OutputType == OutputType.PrimaryGoogle)
Could this be combined with an "or" clause above?

2019-08-17 22:05 UTC, jamesgurung commented on src/CalendarWriters/Google/GoogleCalendarEventComparer.cs
> -﻿using System.Collections.Generic;
The changes made to this file revert my previous commits. Can you update your version of this file to [the original](https://github.com/jamesgurung/timetable-calendar-generator/blob/master/src/CalendarWriters/Google/GoogleCalendarEventComparer.cs).

2019-08-17 22:05 UTC, jamesgurung commented on src/CalendarWriters/Google/GoogleCalendarWriter.cs
> -    private static readonly GoogleCalendarEventComparer _comparer = new GoogleCalendarEventComparer();
The changes made to this file revert my previous commits. Can you update your version of this file to [the original](https://github.com/jamesgurung/timetable-calendar-generator/blob/master/src/CalendarWriters/Google/GoogleCalendarWriter.cs).

2019-08-17 22:05 UTC, jamesgurung commented on src/InputReader.cs
> -    private static readonly string settingsFileName = @"inputs\settings.json";
How come these have changed? Does it make a difference on Linux? You can remove the `@` string prefixes if there are no backslashes.

2019-08-17 22:05 UTC, jamesgurung commented on src/Lesson.cs
> +    public int? YearGroup {
Revert
```suggestion
    public int? YearGroup
    {
```

2019-08-17 22:05 UTC, jamesgurung commented on src/Settings.cs
> -    public IList<Override> Overrides
The changes made to this file revert my previous commits. Can you update your version of this file to the [original](https://github.com/jamesgurung/timetable-calendar-generator/blob/master/src/Settings.cs).

2019-08-18 06:31 UTC, timmy-mac commented on src/CalendarWriterFactory.cs
> +      else if (OutputType == OutputType.PrimaryGoogle)
Yes! Done.

2019-08-18 06:34 UTC, timmy-mac commented on src/InputReader.cs
> -    private static readonly string settingsFileName = @"inputs\settings.json";
I'd forgotten about these. Yes, I was getting 'no file or directory' or whatever on Linux.  Given close links to SIMS and the Windows environment, I think it makes sense to revert them if you want. That said, it seems to work on Windows anyway...

2019-08-18 06:47 UTC, timmy-mac commented on src/ArgumentParser.cs
> +            Console.WriteLine("WARNING: The --primarygoogle option deletes any calendars named 'My timetable'.\nIt will also input events into users' primary calendars...\n\nHit ctrl+c or close the w
This is definitely more elegant than a time delay.  I was too lazy to look up how to read the y/n input!  It does stand in the way of automation through scripting/scheduled tasks though.

2019-08-18 06:51 UTC, timmy-mac commented
No worries! I'm about 10 years overdue a contribution to an open source project.. thanks for sharing your efforts in the first place.

Next step is learning to use Git properly. I think I've put your changes back in and merged your suggestions. Last remaining one is whether you want to revert the forward/back slash thing.

2019-08-18 10:57 UTC, jamesgurung commented on src/InputReader.cs
> -    private static readonly string settingsFileName = @"inputs\settings.json";
If it works on Windows both ways then it's best to keep the version that supports Linux too.

2019-08-18 11:01 UTC, jamesgurung commented on src/ArgumentParser.cs
> +            Console.WriteLine("WARNING: The --primarygoogle option deletes any calendars named 'My timetable'.\nIt will also input events into users' primary calendars...\n\nHit ctrl+c or close the w
Good point. I think the answer is to remove this check altogether. You've already documented the risks clearly in the readme.

2019-08-18 13:43 UTC, merged

2019-08-18 15:25 UTC, jamesgurung commented
Implements #4